OBJECTS = main.o

EXEC = capy

DEPS =  libcapybara:gcc libfxl:gcc libads:gcc libio:gcc \
				libmspware:gcc  libradio:gcc libmsp:gcc libmspuartlink:gcc

override CFLAGS +=  -DRUN_ADC

include tools/maker/Makefile




