OBJECTS = main.o rsa.o


EXEC = atomic_ble

DEPS =  liblsm:gcc libfakecatnap:gcc libcapybara:gcc \
       libfxl:gcc libads:gcc libio:gcc libradio:gcc\
				libmspware:gcc libmsp:gcc libmspuartlink:gcc

override CFLAGS += -I../../data/

include tools/maker/Makefile




